"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ

from apps.core.secrets import secrets

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize django-environ
env = environ.Env(
    DJANGO_ENV=(
        str,
        "development",
    ),
)

# Read .env file if exists (only for development)
env_file = BASE_DIR / ".env"
if env_file.exists():
    env.read_env(env_file)

# Environment
DJANGO_ENV = env("DJANGO_ENV", default="development")
PRODUCTION_ENVS = ("staging", "production")
IS_PRODUCTION = DJANGO_ENV in PRODUCTION_ENVS

# Security settings
if IS_PRODUCTION:
    SECRET_KEY = secrets.get_required("SECRET_KEY")
else:
    SECRET_KEY = env(
        "SECRET_KEY",
        default="django-insecure-dev-only-not-for-production",
    )

DEBUG = env.bool("DEBUG", default=False)

# Validate DEBUG and environment consistency
if IS_PRODUCTION and DEBUG:
    raise ValueError(
        "DEBUG=True is not allowed when DJANGO_ENV=production. "
        "Set DEBUG=False or change DJANGO_ENV."
    )


def _validate_required_secrets() -> None:
    if DJANGO_ENV not in ("staging", "production"):
        return
    required_secrets = ["SECRET_KEY", "REDIS_PASSWORD", "AWS_SECRET_ACCESS_KEY"]
    missing = [key for key in required_secrets if secrets.get(key) is None]
    if missing:
        raise RuntimeError(
            f"Missing required secrets for {DJANGO_ENV} environment: "
            f"{', '.join(missing)}. Set these environment variables before starting."
        )


_validate_required_secrets()

ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1"] if not IS_PRODUCTION else [],
)

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_prometheus",
    "apps.accounts",
    "apps.convocatories",
    "apps.applications",
    "apps.scoring",
    "apps.claims",
    "apps.legalization",
    "apps.treasury",
    "apps.academic_tracking",
    "apps.psychosocial",
    "apps.condonation",
    "apps.governance",
    "apps.reporting",
    "apps.audit",
    "apps.core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "apps.core.middleware.RequestIDMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
DATABASES = {
    "default": env.db(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    ),
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "es-CO"

TIME_ZONE = "America/Bogota"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Redis and Celery
REDIS_URL = env("REDIS_URL", default="redis://localhost:6379/0")
if IS_PRODUCTION:
    REDIS_PASSWORD = secrets.get_required("REDIS_PASSWORD")
else:
    REDIS_PASSWORD = env("REDIS_PASSWORD", default="")

if REDIS_PASSWORD:
    CELERY_BROKER_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_URL.split('://')[1]}"
else:
    CELERY_BROKER_URL = REDIS_URL

CELERY_RESULT_BACKEND = CELERY_BROKER_URL

# S3/MinIO Storage
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID", default="minioadmin")
if IS_PRODUCTION:
    AWS_SECRET_ACCESS_KEY = secrets.get_required("AWS_SECRET_ACCESS_KEY")
else:
    AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY", default="minioadmin")
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME", default="fodejas-media")
AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL", default="http://localhost:9000")
AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="us-east-1")
AWS_S3_SIGNATURE_VERSION = env("AWS_S3_SIGNATURE_VERSION", default="s3v4")
AWS_DEFAULT_ACL = env("AWS_DEFAULT_ACL", default=None)
AWS_S3_FILE_OVERWRITE = env.bool("AWS_S3_FILE_OVERWRITE", default=False)

# Development settings
INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
]

# Logging configuration
LOG_LEVEL = env("LOG_LEVEL", default="DEBUG" if not IS_PRODUCTION else "INFO")

if IS_PRODUCTION:
    from apps.core.logging_config import setup_async_logging

    setup_async_logging(is_production=True)

    import sentry_sdk
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=env("SENTRY_DSN", default=""),
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
        ],
        traces_sampler=None,
        send_default_pii=False,
    )
    sentry_sdk.set_tag("django.env", DJANGO_ENV)
else:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s",
                "style": "%",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "verbose",
            },
        },
        "root": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
        },
        "loggers": {
            "django": {
                "handlers": ["console"],
                "level": LOG_LEVEL,
                "propagate": False,
            },
        },
    }
